---
- name: Packages | Install common packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - git
    - htop
    - nano
    - nfs-common
    - openssh-server
    - sudo

- name: Packages | Install monitoring packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - prometheus-node-exporter

- name: Packages | Install qemu-guest-agent
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - qemu-guest-agent
  when:
    - ansible_virtualization_role == "guest"

  notify: Start qemu
- name: Packages | Install RPi packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    autoclean: true
  loop:
    - linux-modules-extra-raspi
    - rpi-eeprom
  when:
    - "'raspi' in ansible_kernel"
  notify: Reboot
